version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.9
      - test-3.8
      - test-3.7
      - upload:
          requires: [test-3.7, test-3.8, test-3.9]
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

jobs:
  test-3.9: &test-template
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements.test.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            nosetests -vv --with-coverage --cover-erase --cover-package=nd_okta_auth
      - run:
          name: pep8
          command: |
            . venv/bin/activate
            python setup.py pep8
      - run:
          name: black
          command: |
            . venv/bin/activate
            black nd_okta_auth

  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8

  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  upload:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: build package
          command: |
            pip install twine
            python setup.py sdist
      - run:
          name: upload package
          command: |
            twine upload dist/*
